# Generated by Django 6.1 on 2026-09-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0150_pendingagentaction_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseapikey",
            name="scope",
            field=models.CharField(
                choices=[
                    ("read", "Read only"),
                    ("write", "Read and write (no deletes, no emailing students)"),
                    ("admin", "Full course admin (deletes, resets, emailing students)"),
                ],
                default="read",
                help_text="How much this key may do. Agent tools are filtered by it: a key never even sees the tools above its scope. 'read' is the safe default.",
                max_length=8,
            ),
        ),
    ]
