# Generated by Django 6.1 on 2026-10-04 16:35

import re

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


_PUBLIC_CLASS_RE = re.compile(
    r"\bpublic\s+(?:final\s+|abstract\s+)*class\s+([A-Za-z_$][A-Za-z0-9_$]*)"
)


def _derive_name(category_name, script):
    """Filename for the wrapped legacy script: the public class if present,
    else a .java named after the category."""
    m = _PUBLIC_CLASS_RE.search(script or "")
    if m:
        return f"{m.group(1)}.java"
    safe = re.sub(r"[^A-Za-z0-9_]", "_", category_name or "Test") or "Test"
    return f"{safe}.java"


def wrap_scripts(apps, schema_editor):
    TestCategory = apps.get_model("core", "TestCategory")
    TestCategoryFile = apps.get_model("core", "TestCategoryFile")
    for cat in TestCategory.objects.exclude(testScript="").exclude(testScript=None):
        # Idempotent: skip if the category already has files.
        if cat.testFiles.exists():
            continue
        TestCategoryFile.objects.create(
            category=cat, name=_derive_name(cat.name, cat.testScript),
            content=cat.testScript, sortKey=0,
        )


def unwrap_scripts(apps, schema_editor):
    # Reverse is a no-op: testScript is left intact, so wrapping is non-destructive.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_alter_environment_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCategoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(help_text="File name, e.g. 'FooTest.java'.", max_length=255)),
                ('content', models.TextField(blank=True, default='', help_text="The file's source contents.")),
                ('sortKey', models.IntegerField(default=0, help_text='Integer to specify display order.')),
                ('category', models.ForeignKey(help_text='The related test category.', on_delete=django.db.models.deletion.CASCADE, related_name='testFiles', to='core.testcategory')),
            ],
            options={
                'ordering': ['sortKey', 'id'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.RunPython(wrap_scripts, unwrap_scripts),
    ]
